# docker-compose -f docker-compose.env.llms.yml --env-file .env up -d
version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mindsdb_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mindsdb.sql:/docker-entrypoint-initdb.d/mindsdb.sql:ro # O sufixo ":ro" indica que o arquivo será montado como "read-only" (somente leitura) dentro do container. Isso é uma prática comum e segura para scripts de inicialização, pois evita que o container altere o arquivo original no host.

  mindsdb:
    image: mindsdb/mindsdb:latest
    container_name: mindsdb_container
    restart: always
    environment:
      MINDSDB_APIS: http,mysql
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "47334:47334"
      - "47335:47335"
    volumes:
      - mindsdb_data:/root/mdb_storage
    depends_on:
      - mysql

volumes:
  mysql_data:
  mindsdb_data:
